force-app/main/default/objects/Soil_Survey__c/Soil_Survey__c.object-meta.xml
<CustomObject>
    <label>Soil Survey</label>
    <nameField>
        <label>Soil Survey</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Soil Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Soil_Survey__c/fields/awc_r__c.field-meta.xml
<CustomField>
    <fullName>awc_r__c</fullName>
    <label>awc_r</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Soil_Survey__c/fields/aws025wta__c.field-meta.xml
<CustomField>
    <fullName>aws025wta__c</fullName>
    <label>aws025wta</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Soil_Survey__c/fields/chkey__c.field-meta.xml
<CustomField>
    <fullName>chkey__c</fullName>
    <label>chkey</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Soil_Survey__c/fields/cokey__c.field-meta.xml
<CustomField>
    <fullName>cokey__c</fullName>
    <label>cokey</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Soil_Survey__c/fields/compname__c.field-meta.xml
<CustomField>
    <fullName>compname__c</fullName>
    <label>compname</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Soil_Survey__c/fields/drainagecl__c.field-meta.xml
<CustomField>
    <fullName>drainagecl__c</fullName>
    <label>drainagecl</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Soil_Survey__c/fields/elev_r__c.field-meta.xml
<CustomField>
    <fullName>elev_r__c</fullName>
    <label>elev_r</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Soil_Survey__c/fields/ffd_r__c.field-meta.xml
<CustomField>
    <fullName>ffd_r__c</fullName>
    <defaultValue>&quot;0&quot;</defaultValue>
    <label>ffd_r</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Soil_Survey__c/fields/geomdesc__c.field-meta.xml
<CustomField>
    <fullName>geomdesc__c</fullName>
    <label>geomdesc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Soil_Survey__c/fields/irrcapscl__c.field-meta.xml
<CustomField>
    <fullName>irrcapscl__c</fullName>
    <label>irrcapscl</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Soil_Survey__c/fields/kwfact__c.field-meta.xml
<CustomField>
    <fullName>kwfact__c</fullName>
    <label>kwfact</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Soil_Survey__c/fields/mukey__c.field-meta.xml
<CustomField>
    <fullName>mukey__c</fullName>
    <label>mukey</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Soil_Survey__c/fields/muname__c.field-meta.xml
<CustomField>
    <fullName>muname__c</fullName>
    <label>muname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Soil_Survey__c/fields/musym__c.field-meta.xml
<CustomField>
    <fullName>musym__c</fullName>
    <label>musym</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Soil_Survey__c/fields/nirrcapcl__c.field-meta.xml
<CustomField>
    <fullName>nirrcapcl__c</fullName>
    <label>nirrcapcl</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Soil_Survey__c/fields/om_r__c.field-meta.xml
<CustomField>
    <fullName>om_r__c</fullName>
    <label>om_r</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Soil_Survey__c/fields/ph1to1h2o_r__c.field-meta.xml
<CustomField>
    <fullName>ph1to1h2o_r__c</fullName>
    <label>ph1to1h2o_r</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Soil_Survey__c/fields/runoff__c.field-meta.xml
<CustomField>
    <fullName>runoff__c</fullName>
    <label>runoff</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Soil_Survey__c/fields/slope_r__c.field-meta.xml
<CustomField>
    <fullName>slope_r__c</fullName>
    <label>slope_r</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Soil_Survey__c/fields/tfact__c.field-meta.xml
<CustomField>
    <fullName>tfact__c</fullName>
    <label>tfact</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Soil_Survey__c/fields/wsatiated_r__c.field-meta.xml
<CustomField>
    <fullName>wsatiated_r__c</fullName>
    <label>wsatiated_r</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RESTConsumptionClass.cls
public with sharing class RESTConsumptionClass {
    // Where the callout method begins.
    @AuraEnabled
    public static List<Soil_Survey__c> makeCallout()
    {
        List<Soil_Survey__c> surveyList = new List<Soil_Survey__c>();
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('http://47.35.26.53:19740/ssapp/survey/EcA/');
        request.setMethod('GET');
        HttpResponse response = http.send(request);

        if (response.getStatusCode() == 200) {
            Object deserializedResponse = JSON.deserializeUntyped(response.getBody());

            Map<String, Object> respMap = (Map<String, Object>) deserializedResponse;
            List<Object> records = (List<Object>) respMap.get('result');
            
            Map<String, Object> anotherMap = new Map<String, Object>();
            
            for (object record : records)
            {
                anotherMap = (Map<String, Object>) record;
                
                Soil_Survey__c newSurvey = new Soil_Survey__c();    
                newSurvey.awc_r__c = (Decimal) anotherMap.get('awc_r');
                newSurvey.aws025wta__c = (Decimal) anotherMap.get('aws025wta');
                newSurvey.chkey__c = (Integer) anotherMap.get('chkey');
                newSurvey.cokey__c = (Integer) anotherMap.get('cokey');
                newSurvey.compname__c = (String) anotherMap.get('compname');
                newSurvey.drainagecl__c = (String) anotherMap.get('drainagecl');
                newSurvey.elev_r__c = (Integer) anotherMap.get('elev_r');
                newSurvey.ffd_r__c = (Integer) anotherMap.get('ffd_r');
                newSurvey.geomdesc__c = (String) anotherMap.get('geomdesc');
                if (anotherMap.get('irrcapscl') == null)
                {
                    newSurvey.irrcapscl__c = null;
                }
                
                newSurvey.kwfact__c = (Decimal) anotherMap.get('kwfact');
                newSurvey.mukey__c = (Integer) anotherMap.get('mukey');
                newSurvey.muname__c = (String) anotherMap.get('muname');
                newSurvey.musym__c = (Decimal) anotherMap.get('musym');
                newSurvey.nirrcapcl__c = (Decimal) anotherMap.get('nirrcapcl');
                newSurvey.om_r__c = (Decimal) anotherMap.get('om_r');
                newSurvey.ph1to1h2o_r__c = (Decimal) anotherMap.get('ph1to1h2o_r');
                newSurvey.runoff__c = (String) anotherMap.get('runoff');
                newSurvey.slope_r__c = (Integer) anotherMap.get('slope_r');
                newSurvey.tfact__c = (Integer) anotherMap.get('tfact');
                newSurvey.wsatiated_r__c = (Integer) anotherMap.get('wsatiated_r');
                System.debug(anotherMap.get('musym'));
                surveyList.add(newSurvey);
            }
            //return surveyList;
        }
        // System.debug(surveyList);
        return surveyList;
    }
}